### ISSUE TITLE
Missing Headers & Inaccurate / confusing Transaction Type?

### ISSUE THREAD

**Issue by k2skaterii** [steppsr/taxtran#4]
First off...  Thank you.  
The other night I used the command `chia wallet get-transactions > transactions.txt` to export my transactions... Then used some Excel-foo to create a CSV with all the info I needed (or thought I needed).  
The first time I imported transactions from my chia wallet into tax.crypto.com it said I had earned $37k farming Chia.  Whoops, that ain't right - seems like I screwed up!  

The first item is simple.  The CSV output does not have headers.  Not all that hard to figure out what column has what info... Or I can pull it from chiatx.sh `DateTime    Name    Transaction Amount    Current Price    Transaction Type`

I am self pooling - and got lucky twice in a 10 day period.   The +0.25 XCH transactions are when I got lucky.  The 1.75 XCH transactions are when I noticed the wins and claimed rewards from my "pool".  The -2 XCH are me sending the XCH to another wallet.

![chia_wins_Feb](https://user-images.githubusercontent.com/87842648/162557182-294db500-838b-4a22-af61-e79b2f813b6a.png)

Those same transactions in the CSV output labeled the 0.25 XCH transactions as "FEE_REWARD" and the 1.75 XCH transactions as "INCOMING_TX".   Seems like they would or should both be the same?

**Comment by steppsr** [comment]
Hi. Thanks for the feedback. I will add a header to the script, that is a good idea.

For the Transaction Types, I got those directly from Chia Network.
Source: https://github.com/Chia-Network/chia-blockchain/blob/main/chia/wallet/util/transaction_type.py

**Comment by k2skaterii** [comment]
Can't argue with that logic!  

I suppose I understand the a description, filtered my transactions types to only show "FEE_REWARD".  Looks like that's the .25 XCH you earn when you find a block while pooled + any transaction fees that people paid to get their transactions processed NOW.  

The 2 block rewards with more than 0.25 XCH, were during the "first dust storms" that I remember.    

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/kenny/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/kenny/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">


</head>

<body link="#0563C1" vlink="#954F72">



Date / Time | Transaction Amount | Transaction   Type
-- | -- | --
9/4/2021 17:58 | 0.250000000000 | FEE_REWARD
10/22/2021 4:17 | 0.250101000013 | FEE_REWARD
11/1/2021 4:58 | 0.251000001012 | FEE_REWARD
12/2/2021 15:04 | 0.250000000000 | FEE_REWARD
2/16/2022 7:28 | 0.250000000000 | FEE_REWARD
2/26/2022 22:56 | 0.250000000000 | FEE_REWARD



</body>

</html>

**Comment by steppsr** [comment]
That is a good idea for another enhancement... a command line option for selecting a specific Transaction Type. I will add that to the to do list.

**Comment by steppsr** [comment]
@k2skaterii I'm wondering if you tried the latest version and did it get the totaling of transactions correct?

**Comment by k2skaterii** [comment]
Just gave Ver 0.3.1 a whirl...  Took me a couple of minutes to double check my Excel math, turns out it was right.  Seems like the "Change TX" that we were skewing the numbers the other day are still included.  

The OUTGOING_TX was accurate the other day, unfortunately it looks like the OUTGONG_TX values are no longer accurate.  I have 2 transactions at the end of FEB where 2 x XCH left my wallet, those transactions are still there - but each of them is showing up as 0.25 XCH each instead of 2.

IF the alltxs.json & tx_list.csv will help you troubleshoot lemme know and I'll shoot them your way.

**Comment by steppsr** [comment]
If you don't mind that would be great.
